import type { CalculatorInfo } from '@/lib/types';
import { Scale, Activity, PiggyBank, Percent, Landmark, TrendingUp, WalletCards, GitFork, BrainCircuit } from 'lucide-react';

export const calculators: CalculatorInfo[] = [
  {
    id: 'stock-average',
    slug: 'stock-average',
    name: 'Stock Average Calculator',
    description: 'Calculate the average price of stocks purchased at different prices and quantities.',
    path: '/calculators/stock-average',
    icon: Scale,
    color: 'text-sky-500',
  },
  {
    id: 'stock-profit-loss',
    slug: 'stock-profit-loss',
    name: 'Stock Profit/Loss Calculator',
    description: 'Compute profit or loss from stock trades.',
    path: '/calculators/stock-profit-loss',
    icon: Activity,
    color: 'text-emerald-500',
  },
  {
    id: 'sip',
    slug: 'sip',
    name: 'SIP Calculator',
    description: 'Estimate returns on Systematic Investment Plans (SIPs).',
    path: '/calculators/sip',
    icon: PiggyBank,
    color: 'text-amber-500',
  },
  {
    id: 'percentage',
    slug: 'percentage',
    name: 'Percentage Calculator',
    description: 'Perform various percentage-based calculations.',
    path: '/calculators/percentage',
    icon: Percent,
    color: 'text-indigo-500',
  },
  {
    id: 'emi',
    slug: 'emi',
    name: 'EMI Calculator',
    description: 'Calculate Equated Monthly Installments (EMI) for loans.',
    path: '/calculators/emi',
    icon: Landmark,
    color: 'text-rose-500',
  },
  {
    id: 'cagr',
    slug: 'cagr',
    name: 'CAGR Calculator',
    description: 'Compute the Compound Annual Growth Rate for investments.',
    path: '/calculators/cagr',
    icon: TrendingUp,
    color: 'text-lime-500',
  },
  {
    id: 'swp',
    slug: 'swp',
    name: 'SWP Calculator',
    description: 'Calculate systematic withdrawal amounts and remaining balance.',
    path: '/calculators/swp',
    icon: WalletCards,
    color: 'text-cyan-500',
  },
  {
    id: 'stock-split',
    slug: 'stock-split',
    name: 'Stock Split Calculator',
    description: 'Determine the impact of stock splits on share quantity and price.',
    path: '/calculators/stock-split',
    icon: GitFork,
    color: 'text-purple-500',
  },
  {
    id: 'ai-chart-suggestion',
    slug: 'ai-chart-suggestion',
    name: 'AI Chart Suggester',
    description: 'Get AI-powered suggestions for the best chart type for your data.',
    path: '/calculators/ai-chart-suggestion',
    icon: BrainCircuit,
    color: 'text-pink-500',
  }
];
